version: '3'
services:
  grpcox:
    build: .
    ports:
      - "6969:6969"
    volumes:
      - ./index:/index
      - ./log:/log
    env_file:
      - config.env
  kansbile:
    image: mensyli/kansible:040
    ports:
      - "18080:8080"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 13306:3306
    environment:
      MYSQL_ROOT_PASSWORD: xiaoming98

  adminer:
    image: adminer
    restart: always
    ports:
      - 28080:8080
